[package]
name = "janetrs"
version = "0.1.0"
authors = ["Eric Shimizu Karbstein <gr41.j4ck@gmail.com>"]
description = "High level binding for Janet programming language"
repository = "https://github.com/GrayJack/janetrs"
homepage = "https://crates.io/crates/janetrs"
documentation = "https://docs.rs/janetrs"
license-file = "LICENSE"
readme = "README.md"
edition = "2018"
keywords = ["janet", "embedding"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "x86_64-unknown-freebsd",
    "x86_64-unknown-netbsd", "x86_64-apple-darwin", "aarch64-unknown-linux-gnu", "i686-unknown-linux-gnu"]
all-features = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
janet-ll = { git = "https://github.com/GrayJack/janet-ll", branch = "dev" }
bstr = { version = "0.2.13", default-features = false}

[dev-dependencies]
serial_test = "~0.4.0"

[features]
default = ["std", "unicode"]
# To use Error trait and alocations
std = ["bstr/std"]
# Use to have Janet client
amalgation = ["janet-ll/link-amalg"]
# Inline more functions
inline-more = []
# Unicode conveniences
unicode = ["bstr/unicode"]

[[example]]
name = "hello_world"
required-features = ["amalgation"]
