name: Check and Test

on: [push]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [1.43.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
    - name: Check and Run tests
      run: cargo test --features amalgation --verbose

  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        rust: [1.43.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
    - name: Check and Run tests
      run: cargo test --features amalgation --verbose

  # build-windows:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [windows-latest]
  #       rust: [1.43.0, stable, beta, nightly]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: ${{ matrix.rust }}
  #       override: true
  #       profile: minimal
  #   - name: Install LLVM and Clang
  #     uses: KyleMayes/install-llvm-action@v1
  #     with:
  #       version: "12.0"
  #       directory: ${{ runner.temp }}/llvm
  #   - name: Check and Run tests
  #     run: cargo test --features amalgation --verbose
