name: Format test

on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
      - .gitignore
  pull_request:
    paths-ignore:
      - "**.md"
      - "**/LICENSE"
      - .github/FUNDING.yml
      - .editorconfig
      - .gitignore

jobs:
  build:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rustfmt
    - name: Check Format
      run: cargo fmt -- --check